trigger:
  branches:
   include:
     - main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: StaticAnalysis
  condition: always()
  jobs:
  - job: Audit
    condition: always()
    displayName: "Npm Audit"
    steps:
    - checkout: self
      submodules: true
    - task: NodeTool@0
      inputs:
        versionSpec: "22.x"
      displayName: "Install Node.js"
    - task: Npm@1
      displayName: "npm install"
      inputs:
        command: 'install'
        customRegistry: 'useFeed'
        customFeed: 'b8db0229-c220-4583-b1d9-1111e482a1ce'
    - task: Npm@1
      displayName: 'npm audit'
      inputs:
        command: custom
        customCommand: 'audit --audit-level=none'
        customRegistry: 'useFeed'
        customFeed: 'b8db0229-c220-4583-b1d9-1111e482a1ce'
  - job: Snyk
    displayName: 'Build and Snyk Analysis'
    condition: always()
    steps:
      # Step 1: Set up node
      - task: NodeTool@0
        displayName: "Install Node.js"
        inputs:
          versionSpec: "22.x"
      # Step 2: install node
      - task: Npm@1
        displayName: "npm install"
        inputs:
          command: 'install'
          customRegistry: 'useFeed'
          customFeed: 'b8db0229-c220-4583-b1d9-1111e482a1ce'
        # Step 3: build app
      - task: Npm@1
        displayName: 'npm build'
        inputs:
          command: custom
          verbose: false
          customCommand: "run build"
        # Step 4: Install and authenticate Snyk
      - script: |
          npm install -g snyk
          snyk config set endpoint=$(SNYK_ENDPOINT)
          snyk auth $(SNYK_TOKEN)
          set +e
        displayName: 'Snyk Install & Auth'
      # Step 5: Scan code
      - task: SnykSecurityScan@1
        displayName: 'Synk code scan'
        inputs:
          testType: 'code'
          serviceConnectionEndpoint: $(SERVICE_CONNECTION_ENDPOINT) #this is a local variable not library
          monitorWhen: 'always'
          codeSeverityThreshold: 'high'
          failOnIssues: false
      # Step 6: Scan app
      - task: SnykSecurityScan@1
        displayName: 'Synk app scan'
        inputs:
          testType: 'app'
          serviceConnectionEndpoint: $(SERVICE_CONNECTION_ENDPOINT) #this is a local variable not library
          monitorWhen: 'always'
          severityThreshold: 'high'
          failOnIssues: false
          additionalArguments: '--all-projects'    
- stage: BuildAndDeploy
  jobs:
    - job: BuildProd
      condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/main'))
      steps:
        - checkout: self
          submodules: true
        - task: AzureStaticWebApp@0
          inputs:
            app_location: '/' # App source code path relative to cwd
            api_location: '' # Api source code path relative to cwd
            output_location: '_site' # Built app content directory relative to app_location - optional
            azure_static_web_apps_api_token: $(deployment_token)

