version: '3.8'

services:
  eleventy:
    build: .
    container_name: eleventy-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npx eleventy --serve --watch --port=8080"
